# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
image: Visual Studio 2017
branches:
  only:
  - master
  - develop
environment:
  NUGET_API_KEY:
    secure: Cx0q/gQZQpP3eDf6H9lzIDpYYki+sGCpruxgDcFUJRoYdpH7l5aDh7afloH3uNLD
  MYGET_PREVIEW_API_KEY:
    secure: Jy8xwdEWASz3iTL2vr/hfw==
  MYGET_CI_API_KEY:
    secure: Jy8xwdEWASz3iTL2vr/hfw==
  CK_DB_TEST_MASTER_CONNECTION_STRING:
    Server=(local)\SQL2016;Database=master;User ID=sa;Password=Password12!
init:
- git config --global core.autocrlf true
install:
  - ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off